'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MyMovieCollection1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        Friend ReadOnly Property Blue_fullBg_noSideText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue_fullBg_noSideText", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_addCollection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_addCollection", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_search_active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_search_active", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_showDVD_L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_showDVD_L", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_showDvd_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_showDvd_r", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_smallBlue_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_smallBlue_search", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property button_viewDvd_active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_viewDvd_active", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property dvd_starter_kit() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd_starter_kit", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        Friend ReadOnly Property icon_magnifyingGlass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_magnifyingGlass", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property panel_dvdInfo_noTxt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_dvdInfo_noTxt", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property PanelBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PanelBG", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property PanelBG_Tile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PanelBG_Tile", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property Record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Record", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property star_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_empty", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property star_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_filled", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
