'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0525E2PQ81DD7ZTWTK82")> _
        Public Property AmazonSubscriptionId() As String
            Get
                Return CType(Me("AmazonSubscriptionId"), String)
            End Get
            Set(ByVal value As String)
                Me("AmazonSubscriptionId") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("DVD")> _
        Public Property AmazonSearchMode() As String
            Get
                Return CType(Me("AmazonSearchMode"), String)
            End Get
            Set(ByVal value As String)
                Me("AmazonSearchMode") = value
            End Set
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source="".\SQLExpress"";AttachDbFilename=""|DataDirectory|\DVDCollectionDatabas" & _
            "e.mdf"";Integrated Security=True;User Instance=True")> _
        Public ReadOnly Property Connection() As String
            Get
                Return CType(Me("Connection"), String)
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("EN")> _
        Public Property AmazonLocale() As String
            Get
                Return CType(Me("AmazonLocale"), String)
            End Get
            Set(ByVal value As String)
                Me("AmazonLocale") = value
            End Set
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlEN() As String
            Get
                Return CType(Me("AmazonUrlEN"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.co.uk/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlUK() As String
            Get
                Return CType(Me("AmazonUrlUK"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.de/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlDE() As String
            Get
                Return CType(Me("AmazonUrlDE"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.co.jp/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlJP() As String
            Get
                Return CType(Me("AmazonUrlJP"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.fr/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlFR() As String
            Get
                Return CType(Me("AmazonUrlFR"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.ca/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property AmazonUrlCA() As String
            Get
                Return CType(Me("AmazonUrlCA"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")> _
        Public ReadOnly Property MyMovieCollectionUpdatedAWS_AmazonServiceSDK_AWSECommerceService() As String
            Get
                Return CType(Me("MyMovieCollectionUpdatedAWS_AmazonServiceSDK_AWSECommerceService"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.MyMovieCollection1.My.MySettings
            Get
                Return Global.MyMovieCollection1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
